namespace Deepgram.Models;

public class UsageRequest
{
    /// <summary>
    /// Identifier of request.
    /// </summary>
    [JsonPropertyName("request_id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Date/time when request was created.
    /// </summary>
    [JsonPropertyName("created")]
    public DateTime Created { get; set; }

    /// <summary>
    /// Path of endpoint to which request was submitted.
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = string.Empty;

    /// <summary>
    /// Identifier of the API Key with which the request was submitted.
    /// </summary>
    [JsonPropertyName("api_key_id")]
    public string ApiKeyId { get; set; } = string.Empty;

    /// <summary>
    /// Response generated by the request.
    /// </summary>
    /// <remarks>If a response has not yet been generated, this object will be empty.</remarks>
    [JsonPropertyName("response")]
    public UsageRequestResponse Response { get; set; }

    /// <summary>
    /// Only exists if a callback was included in the request.
    /// </summary>
    [JsonPropertyName("callback")]
    public UsageRequestCallback Callback { get; set; }
}
