// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.LiveClientTests.GetBaseUrl_Should_Return_WSS_Protocol_When_DeepgramClientOptions_BaseAddress_Contains_No_Protocol")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.OnPremClientTests.CreateCredentials_Should_Return_CredentialResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.OnPremClientTests.GetCredentials_Should_Call_GetAsync_Returning_CredentialResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.OnPremClientTests.ListCredentials_Should_Call_GetAsync_Returning_CredentialsResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeFile_With_Bytes_Should_Call_PostAsync_Returning_SyncResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeFile_With_Stream_Should_Call_PostAsync_Returning_SyncResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeFileCallBack_With_Bytes_With_CallBack_Parameter_Should_Call_PostAsync_Returning_SyncResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeFileCallBack_With_Bytes_With_CallBack_Property_Should_Call_PostAsync_Returning_SyncResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeFileCallBack_With_Stream_With_CallBack_Parameter_Should_Call_PostAsync_Returning_SyncResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeFileCallBack_With_Stream_With_CallBack_Property_Should_Call_PostAsync_Returning_SyncResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeUrl_Should_Call_PostAsync_Returning_SyncResponse~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeUrlCallBack_Should_Call_PostAsync_Returning_SyncResponse_With_CallBack_Parameter~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests.TranscribeUrlCallBack_Should_Call_PostAsync_Returning_SyncResponse_With_CallBack_Property~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "type", Target = "~T:Deepgram.Tests.UnitTests.ClientTests.OnPremClientTests")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "<Pending>", Scope = "type", Target = "~T:Deepgram.Tests.UnitTests.ClientTests.PrerecordedClientTests")]
