// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_ApiKey_Should_Add_IHttpClientFactory_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_ApiKey_Should_Add_LiveClient_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_ApiKey_Should_Add_ManageClient_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_ApiKey_Should_Add_OnPremClient_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_ApiKey_Should_Add_PrerecordedClient_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_DeepgramClientOptions_Should_Add_IHttpClientFactory_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_DeepgramClientOptions_Should_Add_LiveClient_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_DeepgramClientOptions_Should_Add_ManageClient_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_DeepgramClientOptions_Should_Add_OnPremClient_ToServiceCollection")]
[assembly: SuppressMessage("Spellchecker", "CRRSP08:A misspelled word has been found", Justification = "company name or internal naming not in standard spellcheck dictionary", Scope = "member", Target = "~M:Deepgram.Tests.UnitTests.ExtensionsTests.ServiceCollectionExtensionsTests.AddDeepgram_With_DeepgramClientOptions_Should_Add_PrerecordedClient_ToServiceCollection")]
