namespace Deepgram.Records;

public record GetProjectUsageRequestResponse
{
    /// <summary>
    /// Identifier of request.
    /// </summary>
    [JsonPropertyName("request_id")]
    public string? RequestId { get; set; }

    /// <summary>
    /// Date/time when request was created.
    /// </summary>
    [JsonPropertyName("created")]
    public string? Created { get; set; }

    /// <summary>
    /// Path of endpoint to which request was submitted.
    /// </summary>
    [JsonPropertyName("path")]
    public string? Path { get; set; }

    /// <summary>
    /// Identifier of the API Key with which the request was submitted.
    /// </summary>
    [JsonPropertyName("api_key_id")]
    public string? ApiKeyId { get; set; }

    /// <summary>
    /// Response generated by the request <see cref="Response"/>.
    /// </summary>
    /// <remarks>If a response has not yet been generated, this object will be empty.</remarks>
    [JsonPropertyName("response")]
    public Response? Response { get; set; }

    /// <summary>
    /// Only exists if a callback <see cref="Callback"/> was included in the request.
    /// </summary>
    [JsonPropertyName("callback")]
    public Callback? Callback { get; set; }
}
